source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'cocoa-oauth', '~> 0.0'
pod 'Mantle', '~> 1.5.1'
pod 'pop', '~> 1.0.7'